import './globals.css'
import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div>
      <div className="main-container">
        <Navbar />
        {children}

      </div>
      <Footer />
    </div>
  );
}
