import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel='shortcut icon' href='/images/favicon.ico' />
        <title>Pokedéx</title>
      </Head>
      <body className={inter.className}>
        
        <Navbar />

        {children} 

        <Footer />
      </body>
    </html>
  )
}
